layout = "card"
flow = "stack"

[[item]]
title = "M.S. Computer Science"
subtitle = "Northeastern University"
# icon = "/img/neu_logo.png"
badge = "Sep 2026 - Present"

[[item]]
title = "B.S. Computer Science and Biology"
subtitle = "Northeastern University"
# icon = "/img/neu_logo.png"
badge = "Sep 2022 - Apr 2026"
content = """\
Honors: *Magna Cum Laude*, Dean's List (Fall 2022-Spring 2026)

Awards: Dean's Scholarship (4-year merit-based award)
"""

# [[item]]
# title = "Commonwealth School"
# icon = "/img/neu_logo.png"
# badge = "Sep 2018 - Jun 2022"
