layout = "row"
flow = "stack"

[[item]]
title = "Verizon (Contract)"
subtitle = "Software Engineering Co-op"
icon = "/assets/vz_logo.png"
badge = "Jan - Jul 2025"

[[item]]
title = "Northeastern University"
subtitle = "Algorithms Teaching Assistant"
icon = "/assets/neu_logo.png"
badge = "Sep 2023 - Dec 2024, Sep 2025 - Apr 2026"

[[item]]
title = "UMass Chan Medical School"
subtitle = "Data Analysis Intern"
icon = "/assets/umass_logo.png"
badge = "Jun - Aug 2023"
